---
root: true

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

parser: "@babel/eslint-parser"

plugins:
  - jest
  - babel
  
env:
  node: true
  jest: true
  browser: true

rules:
  no-console: 0
  import/no-extraneous-dependencies: 0
  import/extensions: 0
  no-param-reassign: 0
